FROM node:18 as build

RUN yarn global add pnpm

WORKDIR /app

ARG REACT_APP_API_URL
RUN echo "REACT_APP_API_URL=${REACT_APP_API_URL}" > .env

COPY package*.json ./
RUN pnpm i
COPY . .
RUN pnpm run build

FROM nginx:latest

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80/tcp

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]